# Generated by Django 4.2.20 on 2025-04-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Ganre',
        ),
    ]
